env:
  browser: true
  es6: true
  node: true

extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:import/recommended'
  - 'plugin:import/electron'
  - 'plugin:import/typescript'

plugins:
  - react-refresh

parser: '@typescript-eslint/parser'

settings:
  import/resolver:
    typescript: true
    node: true

rules:
  import/no-unresolved:
    - error
    - commonjs: true
      caseSensitive: true
      ignore:
        - electron
        - \.s?css$
  import/order:
    - error
    - groups: ['builtin', 'external', 'internal', 'parent', 'sibling', 'index']
      newlines-between: 'always'
  '@typescript-eslint/no-namespace': 'off'
  '@typescript-eslint/no-unsafe-declaration-merging': 'off'
  '@typescript-eslint/no-unused-vars':
    - 1
    - argsIgnorePattern: '^_|^config$'

  react-refresh/only-export-components:
    - error
