// this file is auto generated by yakumo, do not edit it manually.
import SatoriServer from "@satoriapp/plugin-satori-server";
import Sqlite from "@satoriapp/plugin-sqlite";

export interface PluginManifest {
  name: string
  meta: Record<string, any>
  version: string
  plugin: any
}

export const plugins: PluginManifest[] = [
  {
    name: "SatoriServer",
    meta: {
    "service": {
        "required": [
            "database",
            "satori"
        ],
        "implements": [
            "satori-server"
        ]
    }
},
    version: "0.0.1",
    plugin: SatoriServer,
  },
  {
    name: "Sqlite",
    meta: {
    "service": {
        "implements": [
            "database"
        ]
    }
},
    version: "0.0.1",
    plugin: Sqlite,
  }
]
