/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Icon: typeof import('./src/components/icon.vue')['default']
    Root: typeof import('./src/components/root.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Spacer: typeof import('./src/components/spacer.vue')['default']
    SystemBar: typeof import('./src/components/systemBar.vue')['default']
    View: typeof import('./src/components/view.vue')['default']
  }
}
